### ISSUE TITLE
Package directories should have README/LICENSE files

### ISSUE THREAD

**Issue by pfitzseb** [timholy/SnoopCompile.jl#106]
Pkg.jl only downloads the package directory, not the whole git repo. This means that you won't have a license or readme locally after `pkg> add SnoppCompileCore`:
```
λ tree SnoopCompileCore       
SnoopCompileCore
└── uT7Ty
    ├── Project.toml
    └── src
        ├── snoopc.jl
        ├── SnoopCompileCore.jl
        ├── snoopi.jl
        └── snoopr.jl
```

It's *possible* that this can be fixed on the Pkg (or package server) side, but for now it'd probably be best to have symlinks/copies in each package dir.

**Comment by KristofferC** [comment]
Yes, it is important to understand that each package in this repo is just a normal package. The way things are structured now makes them more similar to submodules.

**Comment by timholy** [comment]
Yeah, I've realized that what I actually want is the ability to load specific submodules from a package without loading the whole package. The recent Pkg change lets us fake it, but you're absolutely right we should include a few more helper files. Looks like PkgTemplates might need some new features...
