### ISSUE TITLE
Versions in BotConfig and SnoopCompile.yml

### ISSUE THREAD

**Issue by daschw** [timholy/SnoopCompile.jl#115]
In the docs it is highlighted that the versions specified in SnoopCompile.yml have to match the versions in `BotConfig`. In the .yml file I can use the versions
```
      matrix:
        version:   # NOTE: the versions below should match those in your botconfig
          - '1'
          - '1.3'
          - 'nightly'
```
where (I think) `'1'` corresponds to `'1.4.2'` and `'1.3'` to `'1.3.1'`.
However:
```julia
julia> BotConfig("Plots", version = ["1", "1.3", "nightly"]).version
3-element Array{VersionNumber,1}:
 v"1.0.0"
 v"1.3.0"
 v"1.6.0-DEV"
```
Does this mean I have to set the versions to `1.3.1` and `1.4.2` in both (or only BotConfig respectively) and update the versions manually with new julia releases, or is there another way to do this?

**Comment by aminya** [comment]
This the default behavior of `VersionNumber`.

```julia
julia> VersionNumber("1")
v"1.0.0"
```

If we want `v"1"` to mean something else we need to check for that online. 

@timholy What do you think here?

**Comment by timholy** [comment]
I would agree that we should be consistent with the interpretation in the .yml file.

**Comment by aminya** [comment]
@SaschaMann how do you find what `v"1"` stands for in setup-julia?

**Comment by SaschaMann** [comment]
@aminya https://github.com/julia-actions/setup-julia#julia-versions
