### ISSUE TITLE
not working on julia v0.6

### ISSUE THREAD

**Issue by randy3k** [timholy/SnoopCompile.jl#13]
Instead of fixing the existing code, I have written up a script to do the same job. Also, my `parse_call` function is much simpler than the original one.

https://gist.github.com/81313cb89fd7e6c568698d0cab20143f

**Comment by tknopp** [comment]
@randy3k @timholy:

I have tried the SnoopCompile on Julia 0.6 and  it did not work, while the code of @randy3k works. Maybe should this be integrated into SnoopCompile? Or better a new package?

**Comment by timholy** [comment]
I'd be fine with a PR either fixing the existing code or replacing the way it works now with @randy3k's code. A new package would be fine too, but I don't see a good reason to have one broken and one that works.

**Comment by tknopp** [comment]
@randy3k: Could you prepare a pull request?

In the version of @randy3k the intermediate representation is a Dict in memory. One question is if we want to store this as well. This could be interesting if one wants to merge the precompile statements. For instance if modules A,B, C all generate precompile statements for module D, it would be nice if these could be "injected" into module D. This of course only works if no custom types of A,B,C have been used.

**Comment by randy3k** [comment]
I don’t have to time and energy to do a PR now, but I am happy to let any one use my script to prepare a PR.

**Comment by timholy** [comment]
Fixed by #14
