### ISSUE TITLE
Basic example doesn't work

### ISSUE THREAD

**Issue by mateuszbaran** [timholy/SnoopCompile.jl#136]
I was trying to run a basic example from the documentation: https://timholy.github.io/SnoopCompile.jl/stable/snoopr/#A-first-example-1 and it doesn't work:
```julia
julia> using SnoopCompileCore

julia> invalidations = @snoopr f(::Float64) = 2;
ERROR: LoadError: UndefVarError: @snoopr not defined
in expression starting at REPL[2]:1
```
I'm using version 2.1.1 of `SnoopCompileCore`.

**Comment by timholy** [comment]
You need to be running the nightly version of Julia. (See the warning at the top of the page you're looking at.)

**Comment by mateuszbaran** [comment]
Right, I didn't look there. Sorry for opening this issue.
