### ISSUE TITLE
Use more than one branch for automatic PRs

### ISSUE THREAD

**Issue by BeastyBlacksmith** [timholy/SnoopCompile.jl#145]
SnoopCompile in the Plots.jl repository operates only on one branch which causes changes on different branches to reset the PRs to other branches. Is there some configuration, such that there is 1:1 correspondence between precompile update branches and open PR branches?

**Comment by timholy** [comment]
I think this is a question mostly for [CompileBot](https://github.com/aminya/CompileBot.jl)? SnoopCompile now focuses on the analysis and doesn't automate PRs.

**Comment by aminya** [comment]
Yes. This should move to CompileBot. 

The solution is to use derive the branch name from the triggering branch.
https://github.com/JuliaPlots/Plots.jl/blob/17acb456538ced66ec8c2a1c054e221c72b747e6/.github/workflows/SnoopCompile.yml#L83

```
          branch: "SnoopCompile_AutoPR-${{ here! }}"
```

I can figure this out and submit a PR.

**Comment by BeastyBlacksmith** [comment]
> Yes. This should move to CompileBot.

Sure, my fault.. I mixed these up.

> I can figure this out and submit a PR

That'd be great <3
