### ISSUE TITLE
invaldiation_trees throws ERROR: unexpected loctag jl_method_table_disable at 3218

### ISSUE THREAD

**Issue by oxinabox** [timholy/SnoopCompile.jl#146]
I don't have a MWE but from this PR
https://github.com/invenia/Nabla.jl/pull/189#issuecomment-715402593
(I can't reproduce it with the latest release of Nabla)
running

```julia
julia> using SnoopCompileCore

julia> invalidations = @snoopr begin
       using Nabla
       end;

julia> using SnoopCompile

julia> length(uinvalidated(invalidations))
3267

julia> invalidation_trees(invalidations)
ERROR: unexpected loctag jl_method_table_disable at 3218
Stacktrace:
 [1] error(::String, ::String, ::String, ::Int64)
   @ Base ./error.jl:42
 [2] invalidation_trees(list::Vector{Any}; exclude_corecompiler::Bool)
   @ SnoopCompile ~/.julia/packages/SnoopCompile/qKfrD/src/invalidations.jl:294
 [3] invalidation_trees(list::Vector{Any})
   @ SnoopCompile ~/.julia/packages/SnoopCompile/qKfrD/src/invalidations.jl:244
 [4] top-level scope
   @ REPL[9]:1
```

```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1262
Commit 8078eacab7 (2020-10-17 01:19 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
```

**Comment by timholy** [comment]
Something is deleting a method. Do you get any warnings?

**Comment by oxinabox** [comment]
No warning.
Nothing should be deleting a method. This  shows up in a fresh terminal.
Revise is loaded I guess, but not editting concurrently.

We are defining about 1000 methods via `eval` called from `__init__`.

**Comment by timholy** [comment]
Perhaps you're overwriting something that has identical signature? But I thought Julia gives a warning in that case, so it's strange.

The reason I say this is because "jl_method_table_disable" once was the signal from method deletion (https://github.com/JuliaLang/julia/blob/7fa2d39a87ac540f62ea6f7c0ad5f86910d14e2a/src/gf.c#L1549 which calls https://github.com/JuliaLang/julia/blob/7fa2d39a87ac540f62ea6f7c0ad5f86910d14e2a/src/gf.c#L1529-L1534). But it looks like that's been refactored, and these days it seems that can even get thrown from https://github.com/JuliaLang/julia/blob/7fa2d39a87ac540f62ea6f7c0ad5f86910d14e2a/src/gf.c#L1608.

I can replicate if I just check out that PR, right?

**Comment by oxinabox** [comment]
That PR goes to a fair bit of effort to avoid overwriting anything.
But it might. It would be a bug if it was, and I didn't see any warnings

> I can replicate if I just check out that PR, right?

Should be able to, yes

**Comment by timholy** [comment]
Sorry for the delay here. FYI:
```julia
julia> invs[640:650]
11-element Vector{Any}:
 1
  MethodInstance for Branch(::typeof(identity), ::Tuple{Node{var"#s19"} where var"#s19"}, ::Tape)
 2
  MethodInstance for identity(::Node{var"#s19"} where var"#s19")
 3
  MethodInstance for identity(::Node{var"#s19"} where var"#s19")
  "jl_method_table_disable"
  identity(var"273"::Node{var"#s19"} where var"#s19"; kwargs...) in Nabla at /home/tim/.julia/dev/Nabla/src/sensitivities/scalar.jl:5
  "jl_method_table_disable"
```
Fix is coming in #148. For now you should check out `master` (once that merges) because the new `@snoopi_deep` could use some docs and I haven't had time to write them yet.

**Comment by oxinabox** [comment]
So the problem was that some methods get defined twice?
Being able to hunt those down would be useful

**Comment by timholy** [comment]
It should show up as a tree that gives the reason as a method deletion.

**Comment by oxinabox** [comment]
This works great thanks.
With under half an hours work i dropped number of infvalidations from over 3000, to under 200

**Comment by timholy** [comment]
Well done! Hopefully you (or people who use your package in conjunction with other things) will see some immediate benefits! Also `precompile` directives should work better than before, if you care about that.
