### ISSUE TITLE
No methods staleinstances, accumulate_by_source (SnoopCompile v2.4.0)

### ISSUE THREAD

**Issue by Cvikli** [timholy/SnoopCompile.jl#234]
Hey,
I tried to go through the enormous document you made. Really nice features anyway! However I couldn't go through the whole document's examples due to sometimes there where no method matching the mentioned instances. The list of unknown methods: 
- staleinstances ref: https://timholy.github.io/SnoopCompile.jl/stable/snoopi_deep/#A-quick-check-for-potential-invalidations
- accumulate_by_source ref: https://timholy.github.io/SnoopCompile.jl/stable/snoopi_deep_analysis/#methtrigs

Thank you for all the work, I hope I can optimize my code thanks to your tool!

**Comment by Cvikli** [comment]
I see 2.5 has all the capability, just the version wasn't out!
Okay, sorry for bothering! 

] add https://github.com/timholy/SnoopCompile.jl
worked well!

**Comment by timholy** [comment]
Actually, 2.5 was released 6 days ago, you might have just had an old version locally.
