### ISSUE TITLE
SnoopCompile has an error when run on Cxx

### ISSUE THREAD

**Issue by Keno** [timholy/SnoopCompile.jl#3]
Just for fun, I ran this on Cxx, but SnoopCompile failed with the following error:
```
julia> pc, discards = SnoopCompile.parcel(data[end:-1:1,2])
ERROR: c is Cxx.specialize_template(Cxx.ClangCompiler, Cxx.CppPtr{Cxx.CxxQualType{Cxx.CppBaseType{:clang::ClassTemplateDecl}, (false, false, false)}, (false, false, false)}, DataType), fargs is SubString{ASCIIString}["Cxx.specialize_template","Cxx.ClangCompiler, Cxx.CppPtr{Cxx.CxxQualType{Cxx.CppBaseType{:clang::ClassTemplateDecl}, ","false, false, false)}, ","false, false, false)}, DataType)"]
 in error at ./error.jl:22
 in parse_call at /Users/kfischer/.julia/v0.5/SnoopCompile/src/SnoopCompile.jl:145
 in parcel at /Users/kfischer/.julia/v0.5/SnoopCompile/src/SnoopCompile.jl:196
```

**Comment by timholy** [comment]
Should be fixed now.

If you haven't seen it already, you may be interested in the analysis of tradeoffs [here](https://github.com/dcjones/Gadfly.jl/pull/673#issuecomment-136993220). This is sometimes great for the user, but not always ideal for the developer. I often turn off precompilation for a package I'm actively working on, and then hope to remember to turn it back on again when I'm done.
