### ISSUE TITLE
New invalidations CI script?

### ISSUE THREAD

**Issue by ChrisRackauckas** [timholy/SnoopCompile.jl#331]
https://github.com/SciML/LinearSolve.jl/blob/main/.github/workflows/Invalidations.yml is what we have right now.

Is there a better script or some improvements we should be making?

**Comment by timholy** [comment]
Since that just triggers the action, I think that's OK? But see https://github.com/julia-actions/julia-invalidations/issues/10

**Comment by ChrisRackauckas** [comment]
> My best guess is that this is instead intended to count the number of invalidations caused by methods in the package? In which case something like

That's what I meant, the thing seems to give a lot of false alarms so your improvements there are probably necessary. It would be nice to if it also just signaled if invalidations went up, i.e. was a regression test, rather than 0 invalidations which 🤷 always fails right now.
