### ISSUE TITLE
Clarify docs re: precompile and runtime dispatch

### ISSUE THREAD

**Issue by marius311** [timholy/SnoopCompile.jl#349]
The [docs](https://timholy.github.io/SnoopCompile.jl/stable/snoopi_deep_parcel/) state that by running code in precompilation

> It precompiles even the runtime-dispatch dependencies of a command if the dependent methods are in the same package

Is this up-to-date? I was under the impression as of 1.8 you can cache stuff for methods in other packages, but perhaps that's only for fully inferred stuff with no runtime dispatch? (as that sentence seems to suggest to me)

**Comment by timholy** [comment]
Even in 1.8, there's an "ownership" check for all runtime-dispatched items. That's to prevent garbage (setup code, metaprogramming, etc) which is not needed for the package from ending up bloating the cache files. This is basically why SnoopPrecompile exists, to give people an opportunity to tag things as "cache this regardless of ownership."

**Comment by marius311** [comment]
Ah, I see now, thanks.
