### ISSUE TITLE
Failed to precompile SnoopCompile in CI

### ISSUE THREAD

**Issue by ranocha** [timholy/SnoopCompile.jl#397]
We observe the following error in our CI runs:

```
Failed to precompile SnoopCompile [aa65fe97-06da-5843-b5b1-d5d13cad87d2] to "/home/runner/.julia/compiled/v1.11/SnoopCompile/jl_ArRXUZ".
ERROR: LoadError: TypeError: in keyword argument nonoverlayed, expected UInt8, got a value of type Bool
Stacktrace:
   [1] concrete_eval_eligible
     @ ~/.julia/packages/JET/1ZQeA/src/analyzers/jetanalyzer.jl:287 [inlined]
   [2] abstract_call_method_with_const_args(interp::JET.JETAnalyzer{JET.BasicPass}, result::Core.Compiler.MethodCallResult, f::Any, arginfo::Core.Compiler.ArgInfo, si::Core.Compiler.StmtInfo, match::Core.MethodMatch, sv::Core.Compiler.InferenceState, invokecall::Nothing)
     @ Core.Compiler ./compiler/abstractinterpretation.jl:826
[...]
```

see https://github.com/trixi-framework/Trixi.jl/actions/runs/11248379964/job/31277133604?pr=2062#step:5:347

CC @aviatesk (since the stacktrace points to JET.jl)

**Comment by timholy** [comment]
If this comes from `julia-invalidations`, see https://github.com/julia-actions/julia-invalidations/issues/19

**Comment by jmark** [comment]
How about disabling the GH action temporarily till this issue is fixed upstream?

https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/disabling-and-enabling-a-workflow

**Comment by timholy** [comment]
Closing this. The fix is for `julia-invalidations` to bump compat to SnoopCompile v3.
