### ISSUE TITLE
Sorting the result

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#41]
Every time I run the `snoopc` it seems that a new file is generated (which causes duplicate PR in https://github.com/timholy/SnoopCompile.jl/issues/37). Is it possible to sort the result before writing it to the file?

**Comment by timholy** [comment]
If you use `@snoopi`, only the things that weren't successfully precompiled by the old statements will show up. There are some things that Julia refuses to cache (https://github.com/JuliaLang/julia/pull/32705), but in general this greatly reduces duplicates.

I don't know how you'd sort them "rationally," since there is no total order. Maybe alphabetically?

**Comment by aminya** [comment]
Yes, just sorting them alphabetically helps, like how did here:
https://github.com/juliamatlab/MatLang/blob/be7ecfb9914fac6398f846b3b5e941975f801ab1/deps/SnoopCompile/snoopCompile.jl#L82

**Comment by timholy** [comment]
Can you play with the new version (especially under Julia 1.4) and see whether you still want this? The format of the precompile statements has changed quite a bit, especially if there are generated functions, keyword functions, etc. Some of the new precompile statements look like this:

```julia
    let fbody = try __lookup_kwbody__(which(show, (IOStream,MIME{Symbol("image/png")},Array{Gray{Normed{UInt8,8}},2},))) catch missing end
        if !ismissing(fbody)
            precompile(fbody, (Int64,Int64,Function,typeof(show),IOStream,MIME{Symbol("image/png")},Array{Gray{Normed{UInt8,8}},2},))
        end
    end
```

The current sorting order is by time, with the slowest-to-compile coming last.

**Comment by aminya** [comment]
I will test it sometime this week. If the timing is always stable and consistent that can be a good sorting measure.

**Comment by timholy** [comment]
Actually, SnoopCompile 1.1 is already released and contains this change.
