### ISSUE TITLE
Excluding methods dispatched on the types defined in Main

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#42]
In my tests, I defined a couple of types to test my package, however, SnoopCompile generates precompile sentences for these.
We should exclude those from appearing in the precompilition files.
https://github.com/aminya/AcuteML.jl/commit/3e9210af2728e3d63b080f3d8269eb841965028c

**Comment by aminya** [comment]
`SnoopCompile.parcel` seems to do this.

**Comment by timholy** [comment]
Yes, I think this working the way it should.
