### ISSUE TITLE
no precompile sentence from Pkg.test()

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#54]
When I run Pkg.test("somepackage") it doesn't give me any precompile sentence for that `somepackage`.

This makes it hard to use `runtest.jl` for generating a precompile file (a file that is already available for most of the packages).

We can include runtests.jl but because some packages have test dependencies it is hard to add those dependencies to the current environment

**Comment by timholy** [comment]
You understand that `Pkg.test("somepackage")` starts a completely different Julia process, right? So your settings by `@snoopi` don't carry over.

You should be able to circumvent this by starting Julia with `julia --project` and use `include("runtests.jl")`.

**Comment by aminya** [comment]
Ahh, I did not know that. I tried to workaround this by adding test dependencies myself.
 I wrote a function myself that parses a toml and adds the deps. However, I think this feature should be in the [Pkg Instead](https://github.com/JuliaLang/Pkg.jl/issues/1008)
https://github.com/aminya/SnoopCompile.jl/blob/4fe0bf3d3428bbe822d212e5d8ff9d9e0216d1b0/src/utilities.jl#L165
