### ISSUE TITLE
Parcel option for adding extra precompile sentences manually

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#56]
It would be nice if there be a keyword argument for `parcel` to pass some extra precompile sentences manually. 

It should check if the given sentences are not already detected by the `@snoopi` (are not duplicate), and then merge them with the return.

**Comment by timholy** [comment]
What API do you want? A list of signatures?

**Comment by aminya** [comment]
> 
> 
> What API do you want? A list of signatures?

I think a vector should be fine.
What I am thinking about is also a `read` function that does the reverse of what `write` does. To read the signatures from a file and giving a vector for passing to `parcel`.

**Comment by timholy** [comment]
Do you need to specify which package they should be associated with?

**Comment by timholy** [comment]
This has been superseded by SnoopPrecompile.
