### ISSUE TITLE
Multiple OS code precompilation support

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#65]
Can we use something like this?
```julia
@static if Sys.iswindows()
    include("windows/MatLang_precompiles.jl")
      _precompile_()

  elseif Sys.islinux()
    include("linux/MatLang_precompiles.jl")
      _precompile_()

  end
```

**Comment by aminya** [comment]
I tested my proposed solution by adding a `print("windows")` to precompile function, and it seems to work. @timholy Can you confirm this?

**Comment by aminya** [comment]
To solve this I can add a `multios::Bool` option to [`BotConfig`](https://github.com/timholy/SnoopCompile.jl/blob/8d73d1f1d70ca2576e3ef3f6f1d0b80080a4973e/src/bot.jl#L17) that if it is been set to `True`, inside the macro, a new function determines the OS, and moves the generated file to a folder named after the `OS`. And in the end, changes the script to

```
@static if Sys.iswindows()
  include("../deps/SnoopCompile/precompile/windows/precompile_Example.jl")
  _precompile_()

elseif Sys.islinux()
  include("../deps/SnoopCompile/precompile/linux/precompile_Example.jl")
  _precompile_()

end
```

I tried this and it seems to precompile correctly, but I am not sure if `@static` adds any delay or soemthing.

**Comment by timholy** [comment]
This should work. `@static` might not even be necessary, not certain. But it's not bad if you do need it.
