### ISSUE TITLE
Effect on `using` times (after precompilation)

### ISSUE THREAD

**Issue by ericphanson** [timholy/SnoopCompile.jl#74]
In https://gist.github.com/ericphanson/959210a4c44900f2f379a805a0aa3d7c, I tried out generating precompilation statements for the COSMO optimization solver, used through Convex.jl, which relies on the MathOptInterface (MOI) intermediary layer. I found that just adding precompilation statements for COSMO (not Convex or MOI) takes off 15-25 seconds from the first solve (see the third entry in `output.txt` and `output2.txt` in that gist). Which is great! Adding precompile statements for Convex and MOI takes off another 4-8 seconds.

However, these statements add ~25 seconds to the precompilation time, and ~3 seconds to the `using` time (after precompilation). The precompilation time increase is too bad, but I did expect an increase. But the `using` time seems strange, because you'd hope nothing would need to be done if it's already precompiled. Is that to be expected?

Edit: the precompilation statements are available on the `precompile` branch of my fork https://github.com/ericphanson/COSMO.jl.

**Comment by timholy** [comment]
It's expected. More precompiles means that more type-inferred code gets serialized to the `*.ji` file; when it's loaded, all that code has to be deserialized. Short of speeding up Julia's deserializer (which I suspect wouldn't be easy as I imagine it's already been extensively optimized), you may be able to mitigate the impact by aggressive use of the `tmin` parameter, adjusting it to the point where you're happiest with the balance struck.

**Comment by timholy** [comment]
Unless there's something you think this package can do to help or clarify, I'd recommend closing this, but I'll leave that up to you.

**Comment by ericphanson** [comment]
Thanks for the explanation!
