### ISSUE TITLE
SnoopCompile may be too big

### ISSUE THREAD

**Issue by timholy** [timholy/SnoopCompile.jl#95]
I'm a bit concerned about SnoopCompile's growing size. The main issue is that SnoopCompile has tools to spy on the system, but as it adds more of its own methods it introduces ever-more perturbations of that system.

Here's an interesting example: start a fresh REPL (with `--startup-file=no`) and cut-and-paste a "private" version of `@snoopr`, and then use it to snoop on `using SnoopCompile`:

```julia
julia> macro mysnoopr(expr)
           quote
               local list = ccall(:jl_debug_method_invalidation, Any, (Cint,), 1)
               Expr(:tryfinally,
                   $(esc(expr)),
                   ccall(:jl_debug_method_invalidation, Any, (Cint,), 0)
               )
               list
           end
       end
@mysnoopr (macro with 1 method)

julia> invs = @mysnoopr using SnoopCompile
3212-element Array{Any,1}:
  MethodInstance for isempty(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}})
  "invalidate_mt_cache"
  MethodInstance for ==(::Symbol, ::Int64)
  "invalidate_mt_cache"
  MethodInstance for ==(::Char, ::String)
  "invalidate_mt_cache"
  MethodInstance for ==(::Module, ::Module)
  "invalidate_mt_cache"
  MethodInstance for ==(::Expr, ::Int64)
  "invalidate_mt_cache"
  MethodInstance for ==(::TextDisplay, ::REPL.REPLDisplay{REPL.LineEditREPL})
  "invalidate_mt_cache"
  MethodInstance for ==(::Distributed.WorkerState, ::Distributed.WorkerState)
  "invalidate_mt_cache"
  MethodInstance for ==(::Array{String,1}, ::Bool)
  "invalidate_mt_cache"
  MethodInstance for join(::Base.Iterators.Take{Base.Iterators.Repeated{DataType}}, ::String)
  "invalidate_mt_cache"
  MethodInstance for join(::Tuple{Symbol}, ::String)
  "invalidate_mt_cache"
  MethodInstance for join(::Tuple{Symbol,Symbol}, ::String)
  "invalidate_mt_cache"
  MethodInstance for join(::Array{String,1}, ::String, ::String)
  "invalidate_mt_cache"
 ⋮
  MethodInstance for #_print#9(::Int64, ::Bool, ::Bool, ::Any, ::typeof(Pkg.TOML._print), ::Base.GenericIOBuffer{Array{UInt8,1}}, ::AbstractDict, ::Array{String,1})
 0
  MethodInstance for (::Pkg.TOML.var"#_print##kw")(::NamedTuple{(:indent, :first_block, :sorted, :by),_A} where _A<:Tuple, ::typeof(Pkg.TOML._print), ::Base.GenericIOBuffer{Array{UInt8,1}}, ::AbstractDict, ::Array{String,1})
 1
  MethodInstance for (::Pkg.TOML.var"#_print##kw")(::NamedTuple{(:indent, :sorted, :by),_A} where _A<:Tuple, ::typeof(Pkg.TOML._print), ::Base.GenericIOBuffer{Array{UInt8,1}}, ::AbstractDict, ::Array{String,1})
 1
  Tuple{Base.var"#sort!##kw",NamedTuple{(:by,),_A} where _A<:Tuple,typeof(sort!),Any}
  MethodInstance for #_print#9(::Int64, ::Bool, ::Bool, ::Any, ::typeof(Pkg.TOML._print), ::IOStream, ::AbstractDict, ::Array{String,1})
 0
  MethodInstance for (::Pkg.TOML.var"#_print##kw")(::NamedTuple{(:indent, :first_block, :sorted, :by),_A} where _A<:Tuple, ::typeof(Pkg.TOML._print), ::IOStream, ::AbstractDict, ::Array{String,1})
 1
  MethodInstance for (::Pkg.TOML.var"#_print##kw")(::NamedTuple{(:indent, :sorted, :by),_A} where _A<:Tuple, ::typeof(Pkg.TOML._print), ::IOStream, ::AbstractDict, ::Array{String,1})
 1
  Tuple{Base.var"#sort!##kw",NamedTuple{(:by,),_A} where _A<:Tuple,typeof(sort!),Any}
  (::Base.var"#sort!##kw")(::Any, ::typeof(sort!), d::OrderedCollections.OrderedDict) in OrderedCollections at /home/tim/.julia/packages/OrderedCollections/P6ntV/src/dict_sorting.jl:4
  "jl_method_table_insert"
  MethodInstance for fzero(::Base.Broadcast.Broadcasted{LinearAlgebra.StructuredMatrixStyle{T},Axes,F,Args} where Args<:Tuple where F where Axes where T)
 1
  MethodInstance for fzero(::Base.Broadcast.Broadcasted{LinearAlgebra.StructuredMatrixStyle{T},Nothing,typeof(-),_B} where _B<:Tuple where T)
 1
  MethodInstance for any(::typeof(ismissing), ::Any)
  "jl_method_table_insert"
  any(f, node::SnoopCompile.InstanceNode) in SnoopCompile at /home/tim/.julia/dev/SnoopCompile/src/invalidations.jl:49
  "jl_method_table_insert"

julia> length(unique(filter(x->isa(x, Core.MethodInstance), invs)))
1097
```
So, loading SnoopCompile itself invalidates more than 1000 MethodInstances. This is quite bad for a tool that is used to detect invalidations. By calling `invalidation_trees(invs)`, you can see that the overwhelming source of these invalidations is FilePaths.jl, with a small handful contributed by OrderedCollections. But as usual, the fix might be in Julia rather than FilePaths---without looking at FilePaths more carefully, this should not be interpreted as saying that FilePaths is necessarily doing something wrong.

One might worry about some of the other tools, too. SnoopCompile does not have a huge `__init__` function, so this won't force much inference/compilation, and what is done is really essential for `@snoopi` to be able to function. But there's a bit of top-level work in `botutils.jl` (it will compile methods for `Dict{String,String}`, if they aren't already), `deprecations.jl` (the `@eval` statements), `invalidations.jl` (surrounding `which` for `dummyinstance`), `parcel_snoopi.jl` (stuff around `lookup_kwbody_ex` and `default_exclusions`), and the regexs in `src/SnoopCompile.jl` itself. (There are a couple of others but I am pretty sure they aren't a problem or are strictly necessary for even the most minimal functionality.)

I am not quite sure about the best way to address this. One option would be to split out the absolute minimal "core" functionality into one or more packages of their own, and re-export it from SnoopCompile. People who care about this issue could use the micro-package(s) directly. The ability to put multiple packages into a single repo might be nice for this kind of thing.

**Comment by KristofferC** [comment]
Move the Bot stuff to a separate package? Getss rid of YAML and FilePathsBase dependencies and a lot of code.

**Comment by timholy** [comment]
Yes, that is a good option. We could decree that developing it within SnoopCompile made sense to develop the functionality that each needed from the other, but that once developed it makes more sense to split them.

I still wonder, though, if even the parcel/write infrastructure could be more perturbative than we want. It's not a long list of things to worry about, but it's not zero either.

**Comment by aminya** [comment]
> Move the Bot stuff to a separate package? Gets rid of YAML and FilePathsBase dependencies and a lot of code from the more core parts.

That is not a solution since the bot has the same goal as the SnoopCompile. They both should detect compilation properly. 

To remove dependencies we can
- [ ]  write a simple YAML parser to extract `os` and `version`. We can do it by regex.
- [ ] From FilePathsBase only its `walkpath` is  used. Unfortunately Julia's `walkdir` does not provide the same functionality out of th ebox. We can try to write a `walkpath` using `walkdir`.

**Comment by timholy** [comment]
I do think splitting out the bot is technically possible (and is indeed a fairly natural solution), but from a purist's standpoint I wonder if making the measurements using the absolutely-minimal code makes most sense anyway. That is, split `@snoopi`, `@snoopc`, and `@snoopr` out into one or more "micro" packages and let SnoopCompile be everything and the kitchen sink.

I'm a bit interested in playing with the new multiple-packages-in-one-repo (https://github.com/JuliaLang/Pkg.jl/issues/1251), this might be a good time to try it. If it really works well I think it may make maintaining Images.jl a bit easier (it's a pretty tall list of dependencies that need to be co-developed).

**Comment by aminya** [comment]
@timholy Multiple packages in one repo are only needed for their registration. 🤔 Tokenize for example has an internal module called Tokens.
https://github.com/JuliaLang/Tokenize.jl/blob/2a2766a7f0b45d0c506da7568580a0ad33b47611/src/token.jl#L1

**Comment by timholy** [comment]
> Let's remove them

Can't really do that in the 1.x series, but we can in the 2.x series.

> we can use external tools

That has headaches of its own. I'd rather keep everything pure Julia as it is more flexible and has fewer deployment issues. There are other ways to solve this.

> Multiple packages in one repo are only needed for their registration

Right, I've written a few packages with sub-modules (ImageFiltering being an example). My interest though is allowing the *user* to control how much code gets loaded, and that requires the Pkg stuff.

**Comment by aminya** [comment]
> Right, I've written a few packages with sub-modules (ImageFiltering being an example). My interest though is allowing the _user_ to control how much code gets loaded, and that requires the Pkg stuff.

If we use external Julia process there is no need for doing so. The actual snooping process would be clean.
```jl
 julia_cmd = `julia --project=@. -e $snooping_code` 
```

**Comment by timholy** [comment]
That works for `@snoopc`, but both `@snoopi` and `@snoopr` require that you first load SnoopCompile. That's the problem this issue is focused on.

**Comment by aminya** [comment]
> That works for `@snoopc`, but both `@snoopi` and `@snoopr` require that you first load SnoopCompile. That's the problem this issue is focused on.

We we moved the core stuff. this part for example just need to change to `SnoopCompileCore`:
https://github.com/timholy/SnoopCompile.jl/blob/2aeb889d44b496a04005e080c5ef0beda18be794/src/bot/snoop_bench.jl#L10

**Comment by timholy** [comment]
I think we're both saying mostly the same thing: SnoopCompile's ability to collect measurements depends on very little code, and most of the code comes down to analysis.

If we do split out the core, I don't think one needs to spin up a separate process to make the measurements. It's *so* nice that `@snoopi` and `@snoopr` return the actual `MethodInstance`s rather than dumping to a text file that you then have to parse, make sure all dependent packages are reloaded, evaluate, error-handle, and reconstruct. Having the MethodInstances is much of what makes these tools so simple and solid.

**Comment by aminya** [comment]
> I think we're both saying mostly the same thing: SnoopCompile's ability to collect measurements depends on very little code, and the bulk of its code comes down to analysis.
> 
Yes. I agree.

> If we do split out the core, I don't think one needs to spin up a separate process to make the measurements. It's _so_ nice that `@snoopi` and `@snoopr` return the actual `MethodInstance`s rather than dumping to a text file that you then have to parse, make sure all dependent packages are reloaded, evaluate, error-handle, and reconstruct. Having the MethodInstances is much of what makes these tools so simple and solid.

If serialization is not feasible, we should see which part of the analysis is using `MethodInstance` directly. That would be `parcel_snoopi`. I am saying even `parcel_snoopi` may have a bad effect.

**Comment by timholy** [comment]
To be clear, here's what I'm proposing: for users who *really* know what they are doing, the right workflow is
```julia
using SnoopCompileCore
invslist = @snoopr using SomePkg
using SnoopCompile
trees = invalidation_trees(invslist)
```
or
```julia
using SnoopCompileCore
inf_timing = @snoopi tmin=0.01 do_something()
using SnoopCompile
pc = SnoopCompile.parcel(inf_timing)
SnoopCompile.write("/tmp/precompile", pc)
```
This doesn't load `parcel` until after measurements have been collected.

**Comment by aminya** [comment]
> To be clear, here's what I'm proposing: for users who _really_ know what they are doing, the right workflow is
> 
> ```julia
> using SnoopCompileCore
> invslist = @snoopr using SomePkg
> using SnoopCompile
> trees = invalidation_trees(invslist)
> ```
> 
> or
> 
> ```julia
> using SnoopCompileCore
> inf_timing = @snoopi tmin=0.01 do_something()
> using SnoopCompile
> pc = SnoopCompile.parcel(inf_timing)
> SnoopCompile.write("/tmp/precompile", pc)
> ```
> 
> This doesn't load `parcel` until after measurements have been collected.

That is a good solution! We will not need external Julia processes. I love it.

**Comment by aminya** [comment]
Considering this solution again https://github.com/timholy/SnoopCompile.jl/issues/95#issuecomment-644899238, there should be three modules! 

- SnoopCompileCore: doing snooping
- SnoopCompileAnalysis: to generate useful data from the Core data
SnoopCompileBot: the rest which runs the above code in an external process:
```julia
using SnoopCompileBot
julia_cmd = """
using SnoopCompileCore
inf_timing = @snoopi tmin=0.01 do_something()
using SnoopCompileAnalysis
pc = SnoopCompile.parcel(inf_timing)
SnoopCompile.write("/tmp/precompile", pc)
"""
 julia_cmd = `julia --project=@. -e $snooping_code` 
run(julia_cmd)
```
