### ISSUE TITLE
SnoopCompileBot deprecations notice

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#99]
Some packages are using `.github/workflows/SnoopCompile.yml`, and inside that, they `add SnoopCompile` and use it. Is there a way that CompatHelper allows us to find these packages and give them some notification that SnoopCompile is updated and they might need to update some of their code?

[Deprecation warnings are just shown passed in GitHub actions and the users may not notice anything](https://github.com/JuliaLang/julia/issues/36326).

One solution might be using CompatHelper:
https://github.com/bcbi/CompatHelper.jl/issues/218

**Comment by timholy** [comment]
I guess the risk is they might not check the logs? I think it's on them :smile:.

**Comment by aminya** [comment]
Part of it is that not very often people read CI log (unless it errors), and that is why we need to have a better way to inform them. My Julia issue was closed, but @christopher-dG mentioned that he can make a new package, that gives us the ability to push the warnings to GitHub's warning system.

**Comment by christopher-dG** [comment]
The actual code is basically done, just needs some grunt work https://github.com/julia-actions/GitHubActions.jl

**Comment by aminya** [comment]
@christopher-dG That is awesome. Could we rename this package to CILogger instead, and implement a different style of logging in one package? We can add more services like Travis, Azure, etc.

**Comment by christopher-dG** [comment]
No, this one is going to be just GitHub Actions (it does more than logging). You could make a meta-package of sorts that aggregates various similar packages if you like.
